name: Build NodeJS
description: 'Build NodeJS'
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
  upload-test-results:
    description: 'Whether to upload test results or not.'
    required: false
    default: 'false'
  run-bdd-test:
    description: 'Whether to run BDD Tests or not.'
    required: false
    default: 'false'
  app-base-dir:
    description: 'The App Base Directory.'
    required: false
    default: '.'
outputs:
  used-cache:
    description: 'Whether the cache was used.'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Build
        run: |
          cd ${{ inputs.app-base-dir }}
          node --version
          npm --version
          yarn --version
        shell: bash

      - name: Cache Dependencies
        if: inputs.caching == 'true'
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ inputs.app-base-dir }}/node_modules
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        id: install
        if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
        run: |
          cd ${{ inputs.app-base-dir }}
          yarn install
          echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build Code
        run: |
          cd ${{ inputs.app-base-dir }}
          yarn run build
        shell: bash

      - name: Lint Code
        run: |
          cd ${{ inputs.app-base-dir }}
          yarn run lint
        shell: bash

      - name: Test Code
        run: |
          cd ${{ inputs.app-base-dir }}
          yarn run test
        shell: bash

      # - name: Test BDD Code
      #   if: inputs.run-bdd-test == 'true'
      #   run: |
      #     cd ${{ inputs.app-base-dir }}
      #     yarn run e2e
      #   shell: bash
          
      # - name: Generate Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()    # run this step even if previous step failed
      #   with:
      #     name: JEST Tests
      #     path: ${{ inputs.app-base-dir }}/reports/jest-*.xml
      #     reporter: jest-junit

      # - name: Upload Test Results
      #   uses: actions/upload-artifact@v3
      #   if: always() 
      #   with:
      #     name: Upload Test Results
      #     path: |
      #       ${{ inputs.app-base-dir }}/reports/jest-*.xml