# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: TFSec Terraform scan
description: 'TFSec Terraform scan'
runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Run Scan
      uses: aquasecurity/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
      with:
        sarif_file: tfsec.sarif

    - name: Upload Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: tfsec.sarif