name: Deploy Terraform Module
on: 
  workflow_call:
    inputs:
      infra-base-dir:
        description: 'The Infra Base Directory.'
        required: false
        default: 'infra'
        type: string
      deploy:
        description: 'Whether to deploy or not.'
        required: false
        default: 'true'
        type: string

jobs:
  sast-tfsec:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Run TFSec
        uses: tychodev321/workflow-templates/.github/actions/tf-sec@main
  deploy:
    needs: [sast-tfsec]
    if: inputs.deploy == 'true'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tychodev321/ubuntu-terraform:main
    steps:
      - name: Deploy
        uses: tychodev321/workflow-templates/.github/actions/terraform-module@main
        with:
          deploy: ${{ github.event.inputs.deploy }}
          infra-base-dir: ${{ github.event.inputs.infra-base-dir }}
