name: Deploy AWS CDK Infra
on: 
  workflow_call:
    inputs:
      environments: # ['dev','test','acpt','prod']
        description: 'The environment the deployment is for.'
        required: false
        default: "['acpt']"
        type: string
      regions: # ['us-east-1','us-west-2']
        description: 'The region the deployment is for.'
        required: false
        default: "['us-east-1']"
        type: string
      infra-base-dir:
        description: 'The Infra Base Directory.'
        required: false
        default: 'infra'
        type: string
      deploy:
        description: 'Whether to deploy or not.'
        required: false
        default: 'true'
        type: string
      destroy:
        description: 'Whether to destroy or not.'
        required: false
        default: 'false'
        type: string
      aws-account-id:
        description: 'The AWS Account the deploy is for.'
        required: false
        type: string

jobs:
  deploy:
    if: inputs.deploy == 'true'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tychodev321/ubuntu-aws-cdk:main
    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
        region: ${{ fromJson(inputs.regions) }}
    steps:
      - name: Setup Github Actions Deploy Keys
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key:  |
            ${{ secrets.TYCHODEV_AWS_CDK_COMMONS_DEPLOY_KEY }}
      - name: Deploy
        uses: tychodev321/workflow-templates/.github/actions/aws-cdk@main
        with:
          caching: 'true'
          environment: ${{ matrix.environment }}
          region: ${{ matrix.region }}
          infra-base-dir: ${{ inputs.infra-base-dir }}
          deploy: ${{ inputs.deploy }}
          destroy: ${{ inputs.destroy }}
          aws-account-id: ${{ inputs.aws-account-id }}
  destroy:
    if: inputs.destroy == 'true'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tychodev321/ubuntu-aws-cdk:main
    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
        region: ${{ fromJson(inputs.regions) }}
    steps:
      - name: Setup Github Actions Deploy Keys
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key:  |
            ${{ secrets.TYCHODEV_AWS_CDK_COMMONS_DEPLOY_KEY }}
      - name: Destroy
        uses: tychodev321/workflow-templates/.github/actions/aws-cdk@main
        with:
          caching: 'true'
          environment: ${{ matrix.environment }}
          region: ${{ matrix.region }}
          infra-base-dir: ${{ inputs.infra-base-dir }}
          deploy: ${{ inputs.deploy }}
          destroy: ${{ inputs.destroy }}
          aws-account-id: ${{ inputs.aws-account-id }}